### ISSUE TITLE
[BUG] Website showing black boxes

### ISSUE THREAD

**Issue by mdcanham** [mrjackwills/adsbdb#64]
**Describe the bug**
adsbdb.com is not displaying any content

**To Reproduce**
1. Go to https://www.adsbdb.com/
3. See error

**Screenshots**
<img width="5132" height="3006" alt="Image" src="https://github.com/user-attachments/assets/5ec2c316-8e67-4024-b4e0-532095ecd87e" />

**Desktop (please complete the following information):**
 - OS: MacOS Sequioa 15.7.1
 - Browser: Chrome 141.0.7390.66 (Official Build) (arm64)

**Comment by mrjackwills** [comment]
Thanks, can you create this issue over at [adsbdb_site](https://www.github.com/mrjackwills/adsbdb_site)

But, before that, try doing a hard refresh of the page, shift + F5 (on windows), or shift + the reload button in browser. I had this problem when first updating the site, it's connected to a Security Headers issue, but it should now be resolved. I've tried visiting the site on multiple browser, on multiple devices, on multiple IP address, and do not suffer this issue.

**Comment by mdcanham** [comment]
@mrjackwills ah, sorry, wrong project. I'll move the issue as I'm still seeing the black boxes on hard refresh.
